export const tiposServicoCarro = [
  "Troca de Óleo",
  "Troca de Óleo + Filtros",
  "Revisão Completa",
  "Troca de Pastilhas de Freio",
  "Troca de Discos de Freio",
  "Troca de Pneu",
  "Alinhamento e Balanceamento",
  "Troca de Correia Dentada",
  "Troca de Bateria",
  "Troca de Embreagem",
  "Troca de Amortecedor",
  "Troca de Velas/Cabos",
  "Ar Condicionado",
  "Diagnóstico",
  "Outro",
];

export const tiposServicoMoto = [
  "Troca de Óleo",
  "Troca de Óleo + Filtros",
  "Revisão Completa",
  "Troca de Pastilhas de Freio",
  "Troca de Pneu",
  "Troca de Corrente/Kit Relação",
  "Troca de Bateria",
  "Troca de Cabo de Embreagem",
  "Troca de Cabo de Acelerador",
  "Regulagem de Carburador",
  "Troca de Velas",
  "Troca de Pinhão/Coroa",
  "Limpeza de Carburador",
  "Balanceamento de Rodas",
  "Diagnóstico",
  "Outro",
];

export const tiposServicoAutoEletrica = [
  "Diagnóstico Eletrônico",
  "Leitura de Códigos OBD",
  "Instalação de Som",
  "Instalação de Alarme",
  "Instalação de Vidro Elétrico",
  "Instalação de Trava Elétrica",
  "Instalação de Rastreador",
  "Instalação de Câmera de Ré",
  "Instalação de Sensor de Estacionamento",
  "Instalação de Central Multimídia",
  "Reparo de Módulo de Injeção",
  "Reparo de Parte Elétrica",
  "Troca de Bateria",
  "Reparo de Alternador",
  "Reparo de Motor de Arranque",
  "Reparo de Ar Condicionado",
  "Instalação de Xenon/LED",
  "Reparo de Vidros Elétricos",
  "Reparo de Painel",
  "Outro",
];
